# Generated by Django 2.1.2 on 2018-10-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, verbose_name='전화번호')),
                ('code', models.IntegerField(verbose_name='확인코드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
            ],
        ),
    ]
