# Generated by Django 2.1.2 on 2018-10-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='User',
            new_name='user',
        ),
    ]
