# Generated by Django 2.1.2 on 2018-10-05 17:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0005_site'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='site',
            unique_together={('user', 'url')},
        ),
    ]
