# Generated by Django 2.1.2 on 2018-10-06 05:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20181006_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='customer_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
