# Generated by Django 2.1.2 on 2018-10-07 03:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_site_customer_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='customer_uid',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='customer_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
