# Generated by Django 2.1.2 on 2018-10-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20181007_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='billing',
            field=models.BooleanField(default=False, verbose_name='빌링등록여부'),
        ),
    ]
