# Generated by Django 2.1.2 on 2018-10-09 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_userprofile_billing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='상태코드')),
                ('headers', models.TextField(blank=True, null=True, verbose_name='헤더')),
                ('error_flag', models.BooleanField(default=False, verbose_name='에러 여부')),
                ('error_msg', models.TextField(blank=True, null=True, verbose_name='에러 메세지')),
                ('response_tiem', models.FloatField(blank=True, null=True, verbose_name='응답시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Site', verbose_name='사이트')),
            ],
        ),
    ]
